BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `SETTINGS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAME`	TEXT NOT NULL,
	`EMAIL`	TEXT NOT NULL,
	`ADDRESS`	TEXT NOT NULL,
	`PHONE`	TEXT NOT NULL,
	`NUMBER`	TEXT NOT NULL,
	`CURRENCY`	TEXT NOT NULL,
	`INVOICE`	TEXT NOT NULL,
	`TERMS`	TEXT NOT NULL,
	`TAX`	REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS `PRODUCTS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAME`	TEXT NOT NULL,
	`PRICE`	REAL NOT NULL,
	`TAXABLE`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `CLIENTS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAME`	TEXT NOT NULL,
	`EMAIL`	TEXT NOT NULL,
	`ADDRESS`	TEXT NOT NULL,
	`PHONE`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `INVOICES` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ID_CLIENTS`	INTEGER NOT NULL,
	`INUMBER`	TEXT NOT NULL,
	`IDATE`	TEXT NOT NULL,
	`ICURRENCY`	TEXT NOT NULL,
	`TAX`	REAL NOT NULL,
	`TERMS`	TEXT,
	`DUEDATE`	TEXT,
	`NOTES`	TEXT,
	`TERMSNOTES`	TEXT,
	`STATUS`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `INVOICES_ROWS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ID_INVOICES`	INTEGER NOT NULL,
	`ID_PRODUCTS`	INTEGER NOT NULL,
	`PRICE`	REAL NOT NULL,
	`QUANTITY`	REAL NOT NULL,
	`TAXABLE`	INTEGER NOT NULL
);
COMMIT;

